### ISSUE TITLE
'FIRInvalidArgumentException', reason: 'Collection path cannot be empty.'

### ISSUE THREAD

**Issue by newbstudent** [MehmetKaranlik/SwiftUIChatApp#1]
Hi, looks like an interesting app, thanks for submitting it here.  As part of my learning processor how to code SwiftUi apps I built it but when running it I get a " Terminating app due to uncaught exception 'FIRInvalidArgumentException', reason: 'Collection path cannot be empty.'   " error.  I have created my own Firebase app, GoogleService-info file, etc. but keep getting this after attempting to login (after manually creating a new user in my firebase project) or registering one via the app

Thanks!

**Comment by MehmetKaranlik** [comment]
Probably due to the difference between our firebase object modeling.
![Ekran Resmi 2022-03-18 21 37 19](https://user-images.githubusercontent.com/89414084/159063744-c02ef0a1-c5f7-4ced-8234-c06529fd3511.png)
